### ISSUE TITLE
Gamemode script changing on a server results in Game Crash

### ISSUE THREAD

**Issue by skybaks** [thommie-echo/TMNext-PlayerState#2]
Steps to replicate game crash:
1. Play on a dedicated server.
2. Change the gamemode script to a different script than the current one. e.g. TrackMania/TimeAttack.Script.txt -> TrackMania/Rounds.Script.txt
3. When the next map loads with the different script, the game will crash.

**Comment by thommie-echo** [comment]
This should be fixed with the latest commit, could you give it a try?
[You can find the files here](https://github.com/thommie-echo/TMNext-PlayerState/tree/main/PlayerState)

If you need it zipped as a plugin please contact me on discord Thommie#8857

**Comment by skybaks** [comment]
Tested out this change at it looks to be working 👍
